// Code generated by musgen-go. DO NOT EDIT.

package manager

import (
	dts "github.com/mus-format/dts-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/varint"
)

var CmdEnvelopeMUS = cmdEnvelopeMUS{}

type cmdEnvelopeMUS struct{}

func (s cmdEnvelopeMUS) Marshal(v CmdEnvelope, bs []byte) (n int) {
	n = raw.TimeUnix.Marshal(v.At, bs)
	return n + ord.ByteSlice.Marshal(v.Bs, bs[n:])
}

func (s cmdEnvelopeMUS) Unmarshal(bs []byte) (v CmdEnvelope, n int, err error) {
	v.At, n, err = raw.TimeUnix.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Bs, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	return
}

func (s cmdEnvelopeMUS) Size(v CmdEnvelope) (size int) {
	size = raw.TimeUnix.Size(v.At)
	return size + ord.ByteSlice.Size(v.Bs)
}

func (s cmdEnvelopeMUS) Skip(bs []byte) (n int, err error) {
	n, err = raw.TimeUnix.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	return
}

var CmdEnvelopeDTS = dts.New[CmdEnvelope](CmdEnvelopeDTM, CmdEnvelopeMUS)

var OutcomeEnvelopeMUS = outcomeEnvelopeMUS{}

type outcomeEnvelopeMUS struct{}

func (s outcomeEnvelopeMUS) Marshal(v OutcomeEnvelope, bs []byte) (n int) {
	n = ServiceIDMUS.Marshal(v.ServiceID, bs)
	n += WorkflowIDMUS.Marshal(v.WorkflowID, bs[n:])
	return n + ord.ByteSlice.Marshal(v.Bs, bs[n:])
}

func (s outcomeEnvelopeMUS) Unmarshal(bs []byte) (v OutcomeEnvelope, n int, err error) {
	v.ServiceID, n, err = ServiceIDMUS.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.WorkflowID, n1, err = WorkflowIDMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Bs, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	return
}

func (s outcomeEnvelopeMUS) Size(v OutcomeEnvelope) (size int) {
	size = ServiceIDMUS.Size(v.ServiceID)
	size += WorkflowIDMUS.Size(v.WorkflowID)
	return size + ord.ByteSlice.Size(v.Bs)
}

func (s outcomeEnvelopeMUS) Skip(bs []byte) (n int, err error) {
	n, err = ServiceIDMUS.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = WorkflowIDMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	return
}

var OutcomeEnvelopeDTS = dts.New[OutcomeEnvelope](OutcomeEnvelopeDTM, OutcomeEnvelopeMUS)

var ServiceIDMUS = serviceIDMUS{}

type serviceIDMUS struct{}

func (s serviceIDMUS) Marshal(v ServiceID, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s serviceIDMUS) Unmarshal(bs []byte) (v ServiceID, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ServiceID(tmp)
	return
}

func (s serviceIDMUS) Size(v ServiceID) (size int) {
	return ord.String.Size(string(v))
}

func (s serviceIDMUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

var WorkflowIDMUS = workflowIDMUS{}

type workflowIDMUS struct{}

func (s workflowIDMUS) Marshal(v WorkflowID, bs []byte) (n int) {
	n = PartIDMUS.Marshal(v.PartID, bs)
	return n + PartSeqMUS.Marshal(v.PartSeq, bs[n:])
}

func (s workflowIDMUS) Unmarshal(bs []byte) (v WorkflowID, n int, err error) {
	v.PartID, n, err = PartIDMUS.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.PartSeq, n1, err = PartSeqMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s workflowIDMUS) Size(v WorkflowID) (size int) {
	size = PartIDMUS.Size(v.PartID)
	return size + PartSeqMUS.Size(v.PartSeq)
}

func (s workflowIDMUS) Skip(bs []byte) (n int, err error) {
	n, err = PartIDMUS.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = PartSeqMUS.Skip(bs[n:])
	n += n1
	return
}

var PartIDMUS = partIDMUS{}

type partIDMUS struct{}

func (s partIDMUS) Marshal(v PartID, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s partIDMUS) Unmarshal(bs []byte) (v PartID, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = PartID(tmp)
	return
}

func (s partIDMUS) Size(v PartID) (size int) {
	return varint.Int.Size(int(v))
}

func (s partIDMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

var PartSeqMUS = partSeqMUS{}

type partSeqMUS struct{}

func (s partSeqMUS) Marshal(v PartSeq, bs []byte) (n int) {
	return varint.Int64.Marshal(int64(v), bs)
}

func (s partSeqMUS) Unmarshal(bs []byte) (v PartSeq, n int, err error) {
	tmp, n, err := varint.Int64.Unmarshal(bs)
	if err != nil {
		return
	}
	v = PartSeq(tmp)
	return
}

func (s partSeqMUS) Size(v PartSeq) (size int) {
	return varint.Int64.Size(int64(v))
}

func (s partSeqMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int64.Skip(bs)
}
